### ISSUE TITLE
[BUG] No HTML element found using CSS selector '[class*="jsx-963945432"]' within 5 seconds

### ISSUE THREAD

**Issue by knipknap** [Second-Hand-Friends/kleinanzeigen-bot#378]
### ✔️ Expected Behaviour

An ad should be created.

### 🐞 Actual Behaviour

The "new ad" page opens, then the error happens before a title is entered into the form.

### 📋 Steps to Reproduce

1. Try to publish any ad.

### 📺 What browsers are you seeing the problem on? (if applicable)

Chrome 131.0.6778.264

### 💻 What operating systems are you seeing the problem on? (if applicable)

Ubuntu 24.04

### 📃 Relevant log output (if applicable)

```
[ERROR] TimeoutError: No HTML element found using CSS selector '[class*="jsx-963945432"]' within 5 seconds.
[PYI-357669:ERROR] Failed to execute script '__main__' due to unhandled exception!
successfully removed temp profile /tmp/uc_cb05wh4f
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hendrikator** [comment]
[INFO] Veröffentliche Anzeige [Pyramiden Puzzle Ed Hardy]...
[INFO]  ... pausiere für 2021 ms ...
[INFO]  ... pausiere für 2031 ms ...
[INFO]  ... pausiere für 1581 ms ...
[FEHLER] TimeoutError: No HTML element found using CSS selector '[class*="jsx-963945432"]' within 5 seconds.
[PYI-1544:ERROR] Failed to execute script '__main__' due to unhandled exception!
successfully removed temp profile C:\Users\Hendrik\AppData\Local\Google\Chrome\User Da

**Comment by Heavenfighter** [comment]
This should be fixed as in #367 because the attribute jsx-963945432 isnt used anymore.

**Comment by knipknap** [comment]
Strange, perhaps the release was not built properly? I am still seeing the issue on a fresh download.

**Comment by deakgit** [comment]
> Strange, perhaps the release was not built properly? I am still seeing the issue on a fresh download.

Same here

**Comment by Heavenfighter** [comment]
Yes, the mentioned fix isnt yet in the release branch.
